# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-05 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commment',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
